build:
	cd joule_thief && make build
	cd small && make build

view:
	cd joule_thief && make view &
	cd small && make view &

kicad:
	cd joule_thief && make kicad
	cd small && make kicad

clean:
	cd joule_thief && make clean
	cd small && make clean

.PHONY: build view kicad clean
